#' @title get SP 500 Historical
#' @param sp500Symbols a list of the the SP 500 or any symbol list 
#' @param e enviroment to stor the data
#' @param startDate  text string date to start
#' @param endDate text string date to end
#' @param sleepTime time to sleep in betweenn
#' @description function that attemps to get the entire sp500 and store it in an enviroment
#' @export
getHistoricalStocks<-function(sp500Symbols, e, startDate = '2000-01-01', endDate = NULL, sleepTime = 3){
  if(is.null(sp500Symbols)){
    sp500Symbols<-c(unlist(strsplit(c("B,BRK,MMM,ABT,ABBV,ACN,ADBE,ADT,AAP,AES,AET,AFL,AMG,A,GAS,APD,ARG,AKAM,AA,AGN,ALXN,ALLE,ADS,ALL,ALTR,MO,AMZN,AEE,AAL,AEP,AXP,AIG,AMT,AMP,ABC,AME,AMGN,APH,APC,ADI,AON,APA,AIV,AAPL,AMAT,ADM,AIZ,T,ADSK,ADP,AN,AZO,AVGO,AVB,AVY,BHI,BLL,BAC,BK,BCR,BXLT,BAX,BBT,BDX,BBBY,BBY,BIIB,BLK,HRB,BA,BWA,BXP,BSX,BMY,BRCM,CHRW,CA,CVC,COG,CAM,CPB,COF,CAH,HSIC,KMX,CCL,CAT,CBG,CBS,CELG,CNP,CTL,CERN,CF,SCHW,CHK,CVX,CMG,CB,CI,XEC,CINF,CTAS,CSCO,C,CTXS,CLX,CME,CMS,COH,KO,CCE,CTSH,CL,CPGX,CMCSA,CMA,CSC,CAG,COP,CNX,ED,STZ,GLW,COST,CCI,CSX,CMI,CVS,DHI,DHR,DRI,DVA,DE,DLPH,DAL,XRAY,DVN,DO,DTV,DFS,DISCA,DISCK,DG,DLTR,D,DOV,DOW,DPS,DTE,DD,DUK,DNB,ETFC,EMN,ETN,EBAY,ECL,EIX,EW,EA,EMC,EMR,ENDP,ESV,ETR,EOG,EQT,EFX,EQIX,EQR,ESS,EL,ES,EXC,EXPE,EXPD,ESRX,XOM,FFIV,FB,FAST,FDX,FIS,FITB,FSLR,FE,FISV,FLIR,FLS,FLR,FMC,FTI,F,FOSL,BEN,FCX,FTR,GME,GPS,GRMN,GD,GE,GGP,GIS,GM,GPC,GNW,GILD,GS,GT,GOOGL,GOOG,GWW,HAL,HBI,HOG,HAR,HRS,HIG,HAS,HCA,HCP,HCN,HP,HES,HPQ,HD,HON,HRL,HSP,HST,HCBK,HUM,HBAN,ITW,IR,INTC,ICE,IBM,IP,IPG,IFF,INTU,ISRG,IVZ,IRM,JEC,JBHT,JNJ,JCI,JOY,JPM,JNPR,KSU,K,KEY,GMCR,KMB,KIM,KMI,KLAC,KSS,KRFT,KR,LB,LLL,LH,LRCX,LM,LEG,LEN,LVLT,LUK,LLY,LNC,LLTC,LMT,L,LOW,LYB,MTB,MAC,M,MNK,MRO,MPC,MAR,MMC,MLM,MAS,MA,MAT,MKC,MCD,MHFI,MCK,MJN,MWV,MDT,MRK,MET,KORS,MCHP,MU,MSFT,MHK,TAP,MDLZ,MON,MNST,MCO,MS,MOS,MSI,MUR,MYL,NDAQ,NOV,NAVI,NTAP,NFLX,NWL,NFX,NEM,NWSA,NEE,NLSN,NKE,NI,NE,NBL,JWN,NSC,NTRS,NOC,NRG,NUE,NVDA,ORLY,OXY,OMC,OKE,ORCL,OI,PCAR,PLL,PH,PDCO,PAYX,PNR,PBCT,POM,PEP,PKI,PRGO,PFE,PCG,PM,PSX,PNW,PXD,PBI,PCL,PNC,RL,PPG,PPL,PX,PCP,PCLN,PFG,PG,PGR,PLD,PRU,PEG,PSA,PHM,PVH,QRVO,PWR,QCOM,DGX,RRC,RTN,O,RHT,REGN,RF,RSG,RAI,RHI,ROK,COL,ROP,ROST,RCL,R,CRM,SNDK,SCG,SLB,SNI,STX,SEE,SRE,SHW,SIAL,SPG,SWKS,SLG,SJM,SNA,SO,LUV,SWN,SE,STJ,SWK,SPLS,SBUX,HOT,STT,SRCL,SYK,STI,SYMC,SYY,TROW,TGT,TEL,TE,TGNA,THC,TDC,TSO,TXN,TXT,HSY,TRV,TMO,TIF,TWX,TWC,TJX,TMK,TSS,TSCO,RIG,TRIP,FOXA,TSN,TYC,USB,UA,UNP,UNH,UPS,URI,UTX,UHS,UNM,URBN,VFC,VLO,VAR,VTR,VRSN,VZ,VRTX,VIAB,V,VNO,VMC,WMT,WBA,DIS,WM,WAT,ANTM,WFC,WDC,WU,WY,WHR,WFM,WMB,WEC,WYN,WYNN,XEL,XRX,XLNX,XL,XYL,YHOO,YUM,ZBH,ZION,ZTS,BP,EXL,RDS,ATVI,BIDU,CHKP,CHTR,CTRX,DISH,ILMN,LBTYA,LMCA,LMCK,LVNTA,MXIM,NXPI,QVCA,SBAC,SIRI,TSLA,VIP,VOD,VRSK,CTB,TWI,CENX,KALU,NOR,NVFY,CMP,XPL,TLR,SLCA,PES,BAS,SSE,TGE,UTIW,FWRD,PTRY,SPTN,VLGEA,CST,DMRC,ACFN,BCOV,JOB,BBSI,ABCO,KELYA,GSAT,NTLS,SPOK,BURL,GMAN,FRAN,PLCE,AEO,GMO,LODE,GORO,UAMY,ARDX,OVAS,XLRN,IMMU,IILG,HTZ,CAR,AWAY,LOCO,PBPB,FRGI,NDLS,BH,UEC,GSM,RTI,BRSS,ORA,NYLD,HTM,GNE,AVA,VVC,GRH,GEVO,REX,SZYM,AMRS"), split = ',')))
  }
  if(is.null(endDate)){endDate<-as.character(Sys.Date())}
  options(error = expression(NULL))
  for ( i in 1:(length(sp500Symbols))){
    try(getSymbols(sp500Symbols[i], warnings=FALSE, env = e, from = startDate, to = endDate, silent=TRUE))
    Sys.sleep(sleepTime )
  }
  print(ls(e))
}
